<a href="https://colab.research.google.com/github/schr0diinger/schr0diinger/blob/main/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Codes/ML DL Lab/iris.csv")
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
x = df.drop('variety',axis=1)
x.head(5)

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
y = df['variety']
y.head(5)

0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
Name: variety, dtype: object

In [ ]:
df['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
l = LabelEncoder()
y = l.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
y_test

array([1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 2,
       2, 2, 1, 0, 1, 0, 0, 1])

# Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lrg = LinearRegression()

lrg.fit(x_train,y_train)

lrg.score(x_train,y_train)*100

92.86550301648711

In [ ]:
lrg.score(x_test,y_test)*100

93.43270022445127

In [ ]:
y_pred_lrg=lrg.predict(x_test)

In [ ]:
y_pred_lrg

array([ 1.20820676,  1.56158172,  1.08908713,  1.29978105, -0.04924641,
        1.43052441,  1.38609416,  1.80754584,  0.234113  ,  2.0621573 ,
       -0.02320077, -0.06960609,  0.04396429,  2.0600473 ,  0.95430747,
        0.00974491,  2.05722086,  1.57453944,  1.95089997,  1.30866696,
        1.16552558,  2.17355384,  1.92279065,  1.79864419,  1.06981563,
       -0.05620851,  1.23941417,  0.0100323 ,  0.06447466,  0.89531615])

In [ ]:
y_test

array([1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 2,
       2, 2, 1, 0, 1, 0, 0, 1])

# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lgrg = LogisticRegression()

lgrg.fit(x_train,y_train)

y_train_prediction = lgrg.predict(x_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
training_data_accuracy = accuracy_score(y_train_prediction, y_train)
print('Accuracy on Training data : ', training_data_accuracy*100)

Accuracy on Training data :  97.5


In [ ]:
y_test_prediction = lgrg.predict(x_test)
testing_data_accuracy = accuracy_score(y_test_prediction, y_test)
print('Accuracy on Testing data : ', testing_data_accuracy*100)

Accuracy on Testing data :  96.66666666666667


In [ ]:
y_test_prediction

array([1, 1, 1, 1, 0, 1, 1, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 2,
       2, 2, 1, 0, 1, 0, 0, 1])

In [ ]:
y_test

array([1, 2, 1, 1, 0, 1, 1, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 2,
       2, 2, 1, 0, 1, 0, 0, 1])

In [ ]:
y_pred=lgrg.predict(x_test)

from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.92      1.00      0.96        11
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix


In [ ]:
print(confusion_matrix(y_test, y_pred, labels=[2,1,0]))

[[ 9  1  0]
 [ 0 11  0]
 [ 0  0  9]]


# Decision Tree

In [ ]:
from sklearn import tree

In [ ]:
dtc = tree.DecisionTreeClassifier()

In [ ]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
x_train_prediction = dtc.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)
print('Accuracy on Training data : ', training_data_accuracy*100)

Accuracy on Training data :  100.0


In [ ]:
x_test_prediction = dtc.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.9333333333333333


In [ ]:
y_preds=dtc.predict(x_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.85      1.00      0.92        11
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.95      0.93      0.94        30
weighted avg       0.94      0.93      0.93        30



In [ ]:
print(confusion_matrix(y_test, y_preds, labels=[2,1,0]))

[[ 8  2  0]
 [ 0 11  0]
 [ 0  0  9]]


# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rmf = RandomForestClassifier()
rmf.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
x_train_prediction = rmf.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)
print('Accuracy on Training data : ', training_data_accuracy*100)

Accuracy on Training data :  100.0


In [ ]:
x_test_prediction = rmf.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.9666666666666667


In [ ]:
y_preds1=dtc.predict(x_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,y_preds1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.85      1.00      0.92        11
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.95      0.93      0.94        30
weighted avg       0.94      0.93      0.93        30



In [ ]:
print(confusion_matrix(y_test, y_preds1, labels=[2,1,0]))

[[ 8  2  0]
 [ 0 11  0]
 [ 0  0  9]]
